export const COLOR_SELECTED_IN_PALETTE = "COLOR_SELECTED_IN_PALETTE";

export const COLOR_SET_DEFAULT = "COLOR_SET_DEFAULT";

export const COLOR_ADDED_TO_PATH = "COLOR_ADDED_TO_PATH";

export const FETCH_PICTURE_REQUEST = "FETCH_PICTURE_REQUEST";

export const FETCH_PICTURE_SUCCESS = "FETCH_PICTURE_SUCCESS";

export const FETCH_PICTURE_FAILURE = "FETCH_PICTURE_FAILURE";

export const FETCH_PICTURES_REQUEST = "FETCH_PICTURES_REQUEST";

export const FETCH_PICTURES_SUCCESS = "FETCH_PICTURES_SUCCESS";

export const FETCH_PICTURES_FAILURE = "FETCH_PICTURES_FAILURE";
